.catalog:
  name: "Website"
  version: "0.1.0"
  description: |
    New Website
  questions:
  - variable: "storage_name"
    label: LDAP Volume
    description: Used to store OpenLDAP files
    required: true
    type: string
  - variable: "openldap_database"
    description: "Database Name"
    label: "Database Name"
    required: true
    type: "string"
  - variable: "volume_driver"
    description: "Where to store persistent data (local, rancher-nfs, ...)"
    label: "Volume Driver"
    required: true
    default: "local"
    type: "string"
openldap:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 389
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 120000
